require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: disable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Include:
    - db/schema.rb

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Metrics/MethodLength:
  Exclude:
    - db/**/*

Metrics/BlockLength:
  Exclude:
    - db/**/*

